# Generated by Django 3.2.23 on 2023-12-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='audio_image')),
            ],
            options={
                'db_table': 'audio_folder',
            },
        ),
        migrations.CreateModel(
            name='AudioFolderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('part', models.IntegerField(blank=True, null=True)),
                ('file', models.ImageField(upload_to='audio_image')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.audiofolder')),
            ],
            options={
                'db_table': 'audio_folder_files',
            },
        ),
    ]
