# Generated by Django 3.2.23 on 2023-12-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofolderfiles',
            name='file',
            field=models.FileField(upload_to='audio_folder_files'),
        ),
    ]
