# Generated by Django 3.2.23 on 2023-12-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_audiofolderfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofolderfiles',
            name='part',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
