# Generated by Django 3.2.23 on 2023-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lookup_image')),
                ('file', models.FileField(blank=True, null=True, upload_to='lookup_file')),
            ],
            options={
                'db_table': 'lookup_field',
            },
        ),
    ]
