# Generated by Django 3.2.23 on 2023-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupfield',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
