# Generated by Django 3.2.23 on 2023-12-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vichar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vivhar_images')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'su_vichar',
            },
        ),
    ]
