# Generated by Django 3.2.23 on 2023-12-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pravachan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='pravanchan_image')),
            ],
            options={
                'db_table': 'pravachan_folder',
            },
        ),
        migrations.CreateModel(
            name='PravachanFolderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('part', models.FloatField(blank=True, null=True)),
                ('file', models.FileField(upload_to='pravanchan_folder_files')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pravachan.pravachan')),
            ],
            options={
                'db_table': 'pravachan_folder_files',
            },
        ),
    ]
